spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Iv23liZM8AxQWfjbKKC9
            client-secret: 603976563f3980ea8cdf613f5b6ada1c973cc8d0
            scope: openid, profile, fhir
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080
        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user
            user-name-attribute: id
