okta:
  oauth2:
    issuer: https://dev-78649566.okta.com/oauth2/default
    audience: api://default
    client-id: 0oahk72um2f9FMKQC5d7
    client-secret: IXCJ4jepc3TGhtsd5niTisodj8DpvT1K_TUV-eEjD1PwsfPpKHLbn8Y1LtJN634E
    scopes: openid, profile, email, offline_access

spring:
  application:
    name: OKTA-INT
